"""

# Project Euler #2

## Summary: 

[Project Euler](https://projecteuler.net/) is a great site for honing your programming skills while learning some math at the same time.

Here's [problem #2](https://projecteuler.net/problem=2):

  Each new term in the [Fibonacci sequence](https://en.wikipedia.org/wiki/Fibonacci_number) is generated by adding the previous two terms.  

  By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


## Product Requirements: 
* Complete the generator function 
* Complete the generator function 
* Use a filter to get even numbers
* Use reduce to get the sum


## Hints
* Read up ...

"""

print("lorem ipsum")
