from user import User

users=[
    User(id=0, login='lsilva', given_name='Leroy', surname='Silva'),
    User(id=1, login='lguerrero', given_name='Lynn', surname='Guerrero'),
    User(id=2, login='mshort', given_name='Mary', surname='Short'),
    User(id=3, login='sgonzalez', given_name='Sandra', surname='Gonzalez'),
    User(id=4, login='mfrench', given_name='Max', surname='French'),
    User(id=5, login='smccarthy', given_name='Sharon', surname='Mccarthy'),
    User(id=6, login='chiggins', given_name='Clara', surname='Higgins'),
    User(id=7, login='bbenson', given_name='Betty', surname='Benson'),
    User(id=8, login='msilva', given_name='Michelle', surname='Silva'),
    User(id=9, login='hbenson', given_name='Helen', surname='Benson'),
    User(id=10, login='mwalters', given_name='Matthew', surname='Walters'),
    User(id=11, login='ahernandez', given_name='Angela', surname='Hernandez'),
    User(id=12, login='lsherman', given_name='Leon', surname='Sherman'),
    User(id=13, login='rmckenzie', given_name='Roland', surname='Mckenzie'),
    User(id=14, login='cmckenzie', given_name='Carlos', surname='Mckenzie'),
    User(id=15, login='keverett', given_name='Kirk', surname='Everett'),
    User(id=16, login='mlee', given_name='Mary', surname='Lee'),
    User(id=17, login='cbartlett', given_name='Christian', surname='Bartlett'),
    User(id=18, login='ashort', given_name='Antonio', surname='Short'),
    User(id=19, login='arobbins', given_name='Arthur', surname='Robbins'),
    User(id=20, login='afrank', given_name='Angela', surname='Frank'),
    User(id=21, login='mjuarez', given_name='Matthew', surname='Juarez'),
    User(id=22, login='mtorres', given_name='Melody', surname='Torres'),
    User(id=23, login='swaters', given_name='Sandra', surname='Waters'),
    User(id=24, login='shansen', given_name='Shelly', surname='Hansen'),
    User(id=25, login='lrivera', given_name='Leon', surname='Rivera'),
    User(id=26, login='echristian', given_name='Eduardo', surname='Christian'),
    User(id=27, login='ebaxter', given_name='Erik', surname='Baxter'),
    User(id=28, login='bmccarthy', given_name='Blanche', surname='Mccarthy'),
    User(id=29, login='cmaldonado', given_name='Christian', surname='Maldonado'),
]
